version: '3.7'

services:
  db:
    image: mysql:5.7
    volumes:
        - ./sql:/docker-entrypoint-initdb.d/0_init.sql
    restart: always
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: test123
        MYSQL_DATABASE: test
        MYSQL_USER: test
        MYSQL_PASSWORD: test123
  
  # jupyter:
  #   image: jupyter/base-notebook
  #   ports:
  #     - 8888:8888